# Generated by Django 4.0.1 on 2022-02-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Myself'},
        ),
    ]
