# Generated by Django 4.0.1 on 2022-02-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('writer_img', models.ImageField(upload_to='testimonials/')),
                ('writer_name', models.CharField(blank=True, max_length=127, null=True)),
                ('writer_position', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
    ]
