# Generated by Django 4.0.1 on 2022-02-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
