# Generated by Django 4.0.1 on 2022-02-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_education_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
